### ISSUE TITLE
Missing attributes in revenue tracking

### ISSUE THREAD

**Issue by jerryjohnjacob** [marcosteixeira/spree_mixpanel#1]
When I call the mixpanel_track_charges method, I'm unable to see details that such as initial referrer, browser details, origin and so on in the Mixpanel dashboard.

I have not done anything explicitly to ensure that these details have been sent, but I thought the behaviour would be similar to what you see when you fire a Mixpanel event from the Javascript side.

Anything I can do to get these details?

Thanks!

**Comment by marcosteixeira** [comment]
Hi @jerryjohnjacob ,
Sorry for the delayed answer.

When you call `mixpanel_track_charges` we send a revenue info to Mixpanel.

Revenue info are under People section. That infos don't act like an mixpanel event.
